theme: jekyll-theme-console
style: dark
title: "Automobili's Blog"
url: "https://automobili.github.io"
baseurl: "/"
header_pages:
  - index.md
  - about.md
  - config.md

plugins:
  - jekyll-octicons
  - jemoji

permalink: /:year/:month/:day/:title/
markdown: kramdown
footer: 'Back to <a href="https://automobili.github.io/">Home</a>'
